jenkinsci/browserstack-integration-plugin

src/main/java/com/browserstack/automate/ci/common/analytics/Analytics.java, src/main/java/com/browserstack/automate/ci/jenkins/AutomateTestDataPublisher.java, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper.java, src/main/resources/com/browserstack/automate/ci/jenkins/AutomateTestAction/summary.jelly, src/main/resources/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper/help-localOptions.html
=> Merging latest code from BrowserStack master into Jenkins CI

pom.xml, src/main/java/com/browserstack/automate/ci/common/analytics/Analytics.java, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapperDescriptor.java, src/main/resources/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper/global.jelly, src/main/resources/plugin.properties
Changes to ensure that tracking of disabling and enabling usage tracking works.
=> Enable anonymous plugin usage tracking

pom.xml, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper.java, src/main/java/com/browserstack/automate/ci/jenkins/local/JenkinsBrowserStackLocal.java, src/main/resources/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper/config.properties, src/main/resources/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper/global.properties, src/main/resources/com/browserstack/automate/ci/jenkins/BrowserStackBuildWrapper/help-credentialsId.html
1. Adding '-jenkins' to the username.
2. Adding the BuildTag to the localIdentifier.
3. Added BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY
4. Bumped BrowserStackLocal version to 1.0.0
=> Some changes for tracking data and backward compatibility

pom.xml, src/main/java/com/browserstack/automate/ci/jenkins/local/JenkinsBrowserStackLocal.java
1.) Fixes the issue where stop method was not stopping the BSL
2.) Fixes the issue where local-identifier was using pound sign(#)
=> Bug fixes 

pom.xml
Update plugin version for Cypress Report release.
Main PR: https://github.com/jenkinsci/browserstack-integration-plugin/pull/37
=> Version Bump for Cypress Report

pom.xml, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackCypressReportFileCallable.java, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackCypressReportForBuild.java, src/main/java/com/browserstack/automate/ci/jenkins/BrowserStackCypressReportPublisher.java
=> Adding support for retrieving files from jenkins agent nodes

pom.xml
Bumping dependencies with vulnerabilities..
=> chore: update dependencies with vulnerabilities

pom.xml
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> [maven-release-plugin] prepare for next development iteration

pom.xml
=> Release new hpi

.github/workflows/ci.yml
=> add: github action for build success on PR

src/main/java/com/browserstack/automate/ci/common/BrowserStackBuildWrapperOperations.java
=> Add environment variable to identify on SDK

pom.xml
Changes for https://github.com/jenkinsci/browserstack-integration-plugin/pull/64
=> OBS 721 Version bump

pom.xml
Bumping browserstack local version
```[tasklist]
```
=> bump browserstack local

src/main/java/com/browserstack/automate/ci/common/BrowserStackBuildWrapperOperations.java
=> fix: do not set local false if no local config

pom.xml
=> Releasing grr support

pom.xml
=> Quality dashboard changes - Release version bump

pom.xml
=> Release 1.2.13

src/main/java/com/browserstack/automate/ci/common/constants/Constants.java, src/main/java/com/browserstack/automate/ci/jenkins/qualityDashboard/QualityDashboardPipelineTracker.java
=> Qd job url stash

pom.xml
=> Release qd api change

pom.xml
=> Version bump - Post release app upload retries

pom.xml
Upgrading `spring-beans` version from `5.3.18` to `5.3.20`
Jira: https://browserstack.atlassian.net/browse/APS-13600
- Freestyle Project
- Pipeline
- Triggering test
- Report Generation
=> APS-13600 spring-beans version upgrade

pom.xml
=> Intg add new version upgrade
